from __future__ import annotations

from loomlib.theme import Theme, hex_to_vwm


def render_vwm_theme(theme: Theme) -> str:
    return f"""# generated by loom

font_family {theme.font_ui}
font_size {theme.font_size_ui}

gap_px {theme.gap_px}
border_width {theme.border_width}

bar_height {theme.bar_height}
bar_outer_gap {theme.bar_outer_gap}

bar_bg {hex_to_vwm(theme.bg_alt)}
bar_fg {hex_to_vwm(theme.fg)}

border_active {hex_to_vwm(theme.border_active)}
border_inactive {hex_to_vwm(theme.border_inactive)}

workspace_current {hex_to_vwm(theme.workspace_current)}
workspace_occupied {hex_to_vwm(theme.workspace_occupied)}
workspace_empty {hex_to_vwm(theme.workspace_empty)}
"""


def render_kitty_theme(theme: Theme) -> str:
    return f"""font_family {theme.font_mono}
font_size {theme.font_size_term}

background_opacity {theme.terminal_opacity}

cursor_shape block
cursor_blink_interval 0
cursor {theme.fg}
cursor_text_color {theme.bg}

selection_background {theme.selection_bg}
selection_foreground {theme.selection_fg}

foreground {theme.fg}
background {theme.bg}

color0  {theme.color0}
color1  {theme.color1}
color2  {theme.color2}
color3  {theme.color3}
color4  {theme.color4}
color5  {theme.color5}
color6  {theme.color6}
color7  {theme.color7}

color8  {theme.color8}
color9  {theme.color9}
color10 {theme.color10}
color11 {theme.color11}
color12 {theme.color12}
color13 {theme.color13}
color14 {theme.color14}
color15 {theme.color15}
"""


def render_rofi_theme(theme: Theme) -> str:
    return f"""* {{
    bg: {theme.bg};
    bg-alt: {theme.bg_alt};
    fg: {theme.fg};
    fg-muted: {theme.fg_muted};
    accent: {theme.accent};
    accent-fg: {theme.accent_fg};
    border: {theme.border_active};
    selection-bg: {theme.selection_bg};
    selection-fg: {theme.selection_fg};
    font: "{theme.font_ui} {theme.font_size_ui}";
}}
"""


def render_nvim_theme(theme: Theme) -> str:
    transparent = "true" if theme.nvim_transparent else "false"
    return f"""return {{
  colorscheme = "{theme.nvim_scheme}",
  variant = "{theme.nvim_variant}",
  transparent = {transparent},
}}
"""


def render_dunst_theme(theme: Theme) -> str:
    return f"""[global]
follow = mouse
width = {theme.dunst_width}
height = {theme.dunst_height}
origin = top-right
offset = {theme.dunst_offset_x}x{theme.dunst_offset_y}
notification_limit = 20
progress_bar = true
progress_bar_height = 10
icon_corner_radius = 0
min_icon_size = 32
max_icon_size = 64

font = {theme.font_ui} {theme.font_size_ui}
corner_radius = {theme.dunst_corner_radius}
frame_width = {theme.dunst_frame_width}
separator_height = 2
padding = 12
horizontal_padding = 12
text_icon_padding = 8

background = "{theme.bg_alt}"
foreground = "{theme.fg}"
frame_color = "{theme.border_active}"

[urgency_low]
background = "{theme.bg_alt}"
foreground = "{theme.fg}"
frame_color = "{theme.border_inactive}"
timeout = {theme.dunst_timeout}

[urgency_normal]
background = "{theme.bg_alt}"
foreground = "{theme.fg}"
frame_color = "{theme.border_active}"
timeout = {theme.dunst_timeout}

[urgency_critical]
background = "{theme.bg}"
foreground = "{theme.selection_fg}"
frame_color = "{theme.accent}"
timeout = 0
"""


def render_picom_theme(theme: Theme) -> str:
    shadow = "true" if theme.picom_shadow else "false"
    return f"""# generated by loom

backend = "glx";
vsync = true;

detect-rounded-corners = true;
detect-client-opacity = true;
unredir-if-possible = false;

rounded-corners = true;
round-borders = {theme.picom_round_borders};

corner-radius = {theme.picom_corner_radius};

shadow = {shadow};
shadow-opacity = {theme.picom_shadow_opacity};
shadow-offset-x = {theme.picom_shadow_offset_x};
shadow-offset-y = {theme.picom_shadow_offset_y};

active-opacity = {theme.picom_active_opacity};
inactive-opacity = {theme.picom_inactive_opacity};
frame-opacity = 1.0;

fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 5;

rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "class_g = 'rofi'",
  "class_g = 'dunst'"
];

wintypes:
{{
  tooltip = {{ fade = true; shadow = true; opacity = 1.0; focus = true; }};
  dock = {{ shadow = false; }};
  dnd = {{ shadow = false; }};
  popup_menu = {{ opacity = 1.0; }};
  dropdown_menu = {{ opacity = 1.0; }};
}};
"""


def render_tmux_theme(theme: Theme) -> str:
    return f"""# generated by loom

set -g status-style "bg={theme.bg_alt},fg={theme.fg}"

set -g pane-border-style "fg={theme.border_inactive}"
set -g pane-active-border-style "fg={theme.border_active}"

set -g message-style "bg={theme.accent},fg={theme.accent_fg}"

set -g status-left-style "bg={theme.bg_alt},fg={theme.accent}"
set -g status-right-style "bg={theme.bg_alt},fg={theme.fg_muted}"

set -g window-status-style "bg={theme.bg_alt},fg={theme.fg_muted}"
set -g window-status-current-style "bg={theme.bg_alt},fg={theme.accent}"

set -g mode-style "bg={theme.accent},fg={theme.accent_fg}"

set -g status-justify left
set -g status-left-length 30
set -g status-right-length 100
"""


def render_fzf_theme(theme: Theme) -> str:
    return f"""# generated by loom
export LOOM_FZF_COLOR_OPTS="--color=bg:{theme.bg},bg+:{theme.selection_bg},fg:{theme.fg},fg+:{theme.selection_fg},hl:{theme.accent},hl+:{theme.accent},info:{theme.fg_muted},prompt:{theme.accent},pointer:{theme.accent},marker:{theme.accent},spinner:{theme.accent},header:{theme.accent}"
"""
