from __future__ import annotations

from loomlib.theme import Theme, hex_to_vwm


def _bool(value: bool) -> str:
    return "true" if value else "false"


def render_vwm_theme(theme: Theme) -> str:
    return f"""# generated by loom

general {{
    border_px {theme.border_width}
    gap_px {theme.gap_px}
}}

theme {{
    bg {hex_to_vwm(theme.bg)}
    surface {hex_to_vwm(theme.bg_alt)}
    text {hex_to_vwm(theme.fg)}
    text_muted {hex_to_vwm(theme.fg_muted)}
    accent {hex_to_vwm(theme.accent)}
    accent_soft {hex_to_vwm(theme.accent_soft)}
    border {hex_to_vwm(theme.border_inactive)}
}}

bar {{
    enabled {_bool(theme.vwm_bar_enabled)}
    background {_bool(theme.vwm_bar_background)}
    modules {theme.vwm_bar_modules}

    icons {_bool(theme.vwm_bar_icons)}
    colors {_bool(theme.vwm_bar_colors)}
    minimal {_bool(theme.vwm_bar_minimal)}

    position {theme.vwm_bar_position}
    height {theme.vwm_bar_height}
    radius {theme.vwm_bar_radius}

    margin_x {theme.vwm_bar_margin_x}
    margin_y {theme.vwm_bar_margin_y}

    content_margin_x {theme.vwm_bar_content_margin_x}
    content_margin_y {theme.vwm_bar_content_margin_y}

    gap {theme.vwm_bar_gap}
    padding_x {theme.vwm_bar_padding_x}
    padding_y {theme.vwm_bar_padding_y}

    volume_bar_enabled {_bool(theme.vwm_bar_volume_bar_enabled)}
    volume_bar_width {theme.vwm_bar_volume_bar_width}
    volume_bar_height {theme.vwm_bar_volume_bar_height}
    volume_bar_radius {theme.vwm_bar_volume_bar_radius}
}}
"""


def render_kitty_theme(theme: Theme) -> str:
    return f"""font_family {theme.font_mono}
font_size {theme.font_size_term}

background_opacity {theme.terminal_opacity}

cursor_shape block
cursor_blink_interval 0
cursor {theme.fg}
cursor_text_color {theme.bg}

selection_background {theme.selection_bg}
selection_foreground {theme.selection_fg}

foreground {theme.fg}
background {theme.bg}

color0  {theme.color0}
color1  {theme.color1}
color2  {theme.color2}
color3  {theme.color3}
color4  {theme.color4}
color5  {theme.color5}
color6  {theme.color6}
color7  {theme.color7}

color8  {theme.color8}
color9  {theme.color9}
color10 {theme.color10}
color11 {theme.color11}
color12 {theme.color12}
color13 {theme.color13}
color14 {theme.color14}
color15 {theme.color15}
"""


def render_rofi_theme(theme: Theme) -> str:
    return f"""* {{
    bg: {theme.bg};
    bg-alt: {theme.bg_alt};
    fg: {theme.fg};
    fg-muted: {theme.fg_muted};
    accent: {theme.accent};
    accent-fg: {theme.accent_fg};
    border: {theme.border_active};
    selection-bg: {theme.selection_bg};
    selection-fg: {theme.selection_fg};
    font: "{theme.font_ui} {theme.font_size_ui}";
    win-width: {theme.rofi_width}%;
    pad: {theme.rofi_padding}px;
    radius: {theme.rofi_border_radius}px;
    lines: {theme.rofi_lines};
    icon-size: {theme.rofi_icon_size}px;
    elem-spacing: {theme.rofi_element_spacing}px;
}}
"""


def render_nvim_theme(theme: Theme) -> str:
    transparent = "true" if theme.nvim_transparent else "false"
    palette = theme.custom_palette()

    if palette:
        palette_lines = "\n".join([f'    {k} = "{v}",' for k, v in palette.items()])
        return f"""return {{
  colorscheme = "{theme.nvim_scheme}",
  variant = "{theme.nvim_variant}",
  transparent = {transparent},
  palette = {{
{palette_lines}
  }},
}}
"""
    return f"""return {{
  colorscheme = "{theme.nvim_scheme}",
  variant = "{theme.nvim_variant}",
  transparent = {transparent},
}}
"""


def render_dunst_theme(theme: Theme) -> str:
    return f"""[global]
follow = mouse
width = {theme.dunst_width}
height = {theme.dunst_height}
origin = top-right
offset = {theme.dunst_offset_x}x{theme.dunst_offset_y}
notification_limit = 20
progress_bar = true
progress_bar_height = 10
icon_corner_radius = 0
min_icon_size = 32
max_icon_size = 64

font = {theme.font_ui} {theme.font_size_ui}
corner_radius = {theme.dunst_corner_radius}
frame_width = {theme.dunst_frame_width}
separator_height = 2
padding = 12
horizontal_padding = 12
text_icon_padding = 8

background = "{theme.bg_alt}"
foreground = "{theme.fg}"
frame_color = "{theme.border_active}"

[urgency_low]
background = "{theme.bg_alt}"
foreground = "{theme.fg}"
frame_color = "{theme.border_inactive}"
timeout = {theme.dunst_timeout}

[urgency_normal]
background = "{theme.bg_alt}"
foreground = "{theme.fg}"
frame_color = "{theme.border_active}"
timeout = {theme.dunst_timeout}

[urgency_critical]
background = "{theme.bg}"
foreground = "{theme.selection_fg}"
frame_color = "{theme.accent}"
timeout = 0
"""


def render_picom_theme(theme: Theme) -> str:
    shadow = "true" if theme.picom_shadow else "false"
    return f"""# generated by loom

backend = "glx";
vsync = true;

detect-rounded-corners = true;
detect-client-opacity = true;
unredir-if-possible = false;

rounded-corners = true;
round-borders = {theme.picom_round_borders};

corner-radius = {theme.picom_corner_radius};

shadow = {shadow};
shadow-opacity = {theme.picom_shadow_opacity};
shadow-offset-x = {theme.picom_shadow_offset_x};
shadow-offset-y = {theme.picom_shadow_offset_y};

active-opacity = {theme.picom_active_opacity};
inactive-opacity = {theme.picom_inactive_opacity};
frame-opacity = 1.0;

use-damage = false;

fading = true;
fade-in-step = {theme.picom_fade_in_step};
fade-out-step = {theme.picom_fade_out_step};
fade-delta = {theme.picom_fade_delta};

rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'"
];

wintypes:
{{
  tooltip = {{ fade = true; shadow = true; opacity = 1.0; focus = true; }};
  dock = {{ shadow = false; }};
  dnd = {{ shadow = false; }};
  popup_menu = {{ opacity = 1.0; }};
  dropdown_menu = {{ opacity = 1.0; }};
}};

blur:
{{
  method = "{"gaussian" if theme.picom_blur_enabled else "none"}";
  size = 2;
  deviation = 5.0;
  strength = 2;
}};

"""


def render_tmux_theme(theme: Theme) -> str:
    return f"""# generated by loom

set -g status-style "bg={theme.bg_alt},fg={theme.fg}"

set -g pane-border-style "fg={theme.border_inactive}"
set -g pane-active-border-style "fg={theme.border_active}"

set -g message-style "bg={theme.accent},fg={theme.accent_fg}"

set -g status-left-style "bg={theme.bg_alt},fg={theme.accent}"
set -g status-right-style "bg={theme.bg_alt},fg={theme.fg_muted}"

set -g window-status-style "bg={theme.bg_alt},fg={theme.fg_muted}"
set -g window-status-current-style "bg={theme.bg_alt},fg={theme.accent}"

set -g mode-style "bg={theme.accent},fg={theme.accent_fg}"

set -g status-justify left
set -g status-left-length 30
set -g status-right-length 100
"""


def render_fzf_theme(theme: Theme) -> str:
    return f"""# generated by loom
export LOOM_FZF_COLOR_OPTS="--color=bg:-1,bg+:-1,fg:{theme.fg},fg+:{theme.selection_fg},hl:{theme.accent},hl+:{theme.accent},info:{theme.fg_muted},prompt:{theme.accent},pointer:{theme.accent},marker:{theme.accent},spinner:{theme.accent},header:{theme.accent}"
"""


def render_session_theme(theme: Theme) -> str:
    gtk_theme = "Adwaita-dark" if theme.ui_mode == "dark" else "Adwaita"
    return f"""# generated by loom
export GTK_THEME={gtk_theme}
"""


def render_gtk_settings(theme: Theme) -> str:
    gtk_theme = "Adwaita-dark" if theme.ui_mode == "dark" else "Adwaita"
    prefer_dark = "1" if theme.ui_mode == "dark" else "0"
    return f"""[Settings]
gtk-theme-name={gtk_theme}
gtk-icon-theme-name=Adwaita
gtk-application-prefer-dark-theme={prefer_dark}
"""
